# Generated by Django 5.2 on 2025-06-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField(help_text='Unique ID from Spoonacular API', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Saved Recipe',
                'verbose_name_plural': 'Saved Recipes',
                'ordering': ['-id'],
            },
        ),
    ]
